# Generated by Django 2.2.7 on 2021-01-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default=' ', max_length=100)),
                ('admin_lastname', models.CharField(default=' ', max_length=100)),
                ('avatar', models.CharField(default=' ', max_length=100)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('username', models.CharField(default=' ', max_length=100)),
                ('password', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_options', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_type', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Money_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_status', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
                ('all_price', models.CharField(default=' ', max_length=100)),
                ('lat', models.CharField(default=' ', max_length=1000)),
                ('lng', models.CharField(default=' ', max_length=1000)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Admin')),
                ('delivery_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Delivery_Options')),
                ('money_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Money_Status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_options', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_products', models.IntegerField()),
                ('Sold', models.IntegerField()),
                ('inventories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default=' ', max_length=100)),
                ('store_img', models.CharField(default=' ', max_length=100)),
                ('store_phone', models.CharField(default=' ', max_length=100)),
                ('adddres', models.CharField(default=' ', max_length=100)),
                ('lat', models.CharField(default=' ', max_length=1000)),
                ('lng', models.CharField(default=' ', max_length=1000)),
                ('time_open', models.CharField(default=' ', max_length=100)),
                ('time_close', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=' ', max_length=100)),
                ('user_lastname', models.CharField(default=' ', max_length=100)),
                ('username', models.CharField(default=' ', max_length=100)),
                ('password', models.CharField(default=' ', max_length=100)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('phone', models.IntegerField()),
                ('avatar', models.CharField(default=' ', max_length=1000)),
                ('lat', models.CharField(default=' ', max_length=1000)),
                ('lng', models.CharField(default=' ', max_length=1000)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=' ', max_length=1000)),
                ('product_price', models.IntegerField()),
                ('product_detail', models.CharField(default=' ', max_length=1000)),
                ('product_img', models.CharField(default=' ', max_length=1000)),
                ('amount', models.IntegerField()),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product_Status')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('payment_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Payment_Options')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('orderproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Payment_Options'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_detail', models.CharField(default=' ', max_length=100)),
                ('mechanic_img', models.CharField(default=' ', max_length=100)),
                ('mechanic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mechanic_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default=' ', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
