# Generated by Django 2.2.7 on 2021-03-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Delivery_Options', verbose_name='ตัวเลือกการจัดส่ง'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Payment_Options', verbose_name='ตัวเลือกการชำระเงิน'),
        ),
    ]
