# Generated by Django 2.2.7 on 2021-03-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lng',
        ),
    ]
