# Generated by Django 2.2.7 on 2021-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_img',
            field=models.ImageField(upload_to='media/', verbose_name='รูปงานช่าง'),
        ),
    ]
