# Generated by Django 2.2.7 on 2021-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lng',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='ที่อยู่ร้าน'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img',
            field=models.ImageField(default='images/store/no-img.png', null=True, upload_to='images/store/', verbose_name='รูปร้าน'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='ชื่อร้าน'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='เบอร์โทรศัพท์ร้าน'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='images/users/no-img.png', upload_to='images/users/', verbose_name='รูปโปรไฟล์'),
        ),
    ]
