# Generated by Django 2.2.7 on 2021-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
