# Generated by Django 2.2.7 on 2021-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=' ', max_length=100, verbose_name='ชื่อ'),
        ),
    ]
