# Generated by Django 2.2.7 on 2021-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='store',
            name='store_detail',
            field=models.CharField(default=' -', max_length=100, null=True, verbose_name='ที่อยู่ร้าน'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default=' ', max_length=100, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
