# Generated by Django 2.2.7 on 2021-05-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='accountName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
