# Generated by Django 2.2.7 on 2021-04-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210424_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_options',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('S', 'โอนผ่านบัญชีธนาคาร'), ('เงินสด', 'เงินสด')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
