# Generated by Django 2.2.7 on 2021-03-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210304_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product_Status', verbose_name='สถานะสินค้า'),
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
        migrations.DeleteModel(
            name='Order_Product',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
