# Generated by Django 2.2.7 on 2021-04-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210426_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutForm',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Payment_Options', verbose_name='ตัวเลือกการชำระเงิน'),
        ),
    ]
