# Generated by Django 2.2.7 on 2021-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_banktransfer_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='qrcode',
            field=models.ImageField(default='images/bankTransfer/no-img.png', null=True, upload_to='images/bankTransfer/', verbose_name='qrcode'),
        ),
    ]
