# Generated by Django 2.2.7 on 2021-02-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
