# Generated by Django 2.2.7 on 2021-03-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
