# Generated by Django 2.2.7 on 2021-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210427_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('โอนผ่านบัญชีธนาคาร', 'โอนผ่านบัญชีธนาคาร'), ('เงินสด', 'เงินสด')], max_length=1),
        ),
    ]
