# Generated by Django 2.2.7 on 2021-05-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210503_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment_Options',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
