# Generated by Django 2.2.7 on 2021-05-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210503_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'verbose_name': 'ข้อมูลบัญชีธนาคาร'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.DeleteModel(
            name='Product_Status',
        ),
    ]
