# Generated by Django 2.2.7 on 2021-03-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
