# Generated by Django 2.2.7 on 2021-03-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210302_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversations',
        ),
    ]
