# Generated by Django 2.2.7 on 2021-03-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='users',
        ),
    ]
