# Generated by Django 2.2.7 on 2021-03-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
