# Generated by Django 2.2.7 on 2021-03-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_order_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
    ]
