# Generated by Django 2.2.7 on 2021-03-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_order_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
