# Generated by Django 2.2.7 on 2021-01-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='images/product/no-img.png', upload_to='images/product/', verbose_name='รูปสินค้า'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img',
            field=models.ImageField(default='images/store/no-img.png', upload_to='images/store/', verbose_name='รูปร้าน'),
        ),
    ]
