# Generated by Django 2.2.7 on 2021-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210129_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='avatar',
            field=models.ImageField(default='images/mechanic/no-img.png', upload_to='images/mechanic/', verbose_name='รูปโปรไฟล์'),
        ),
    ]
